"""Generate the shipping rate cards for the browser and the Worker from the one contracted source.

    python tools/gen-rates.py

    data/rate-cards.json  ->  assets/rate-cards.js   (window.RF_RATE_CARDS, loaded by assets/shipping.js)
                          ->  deploy/rates.gen.js    (export const RATES, bundled into the Worker)

There is exactly one copy of the contracted numbers. The shop, the price export and the API all compute shipping from
this file, so a customer's quoted price and the server's re-priced order can never disagree about the rate.
"""
import io, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "data", "rate-cards.json")
data = json.load(io.open(src, encoding="utf-8"))

cards = data.get("cards", [])
assert cards, "no rate cards"
for c in cards:
    for k in ("id", "mode", "origin", "destination", "unit", "effectiveFrom", "tiers", "transitMinDays", "transitMaxDays"):
        assert c.get(k) not in (None, "", []), "%s is missing %s" % (c.get("id"), k)
    assert c["mode"] in ("air", "sea"), c["id"]
    assert c.get("status") in ("draft", "contracted", "expired"), "%s has a bad status" % c["id"]
    tiers = c["tiers"]
    assert tiers == sorted(tiers, key=lambda t: t["from"]), "%s tiers must ascend by 'from'" % c["id"]
    assert tiers[0]["from"] == 0, "%s needs a tier starting at 0" % c["id"]
    if c["mode"] == "air":
        assert c.get("volumetricDivisor", 0) > 0, "%s needs a volumetric divisor" % c["id"]

# the browser and the Worker get the cards and the density table; the prose notes stay out of the payload
payload = {"cards": cards, "packedDensity": {k: v for k, v in data.get("packedDensity", {}).items() if not k.startswith("_")}}
blob = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))

def write(path, text):
    tmp = path + ".tmp"
    io.open(tmp, "w", encoding="utf-8").write(text)
    os.replace(tmp, path)

write(os.path.join(ROOT, "assets", "rate-cards.js"),
      u"/* GENERATED by tools/gen-rates.py from data/rate-cards.json — do not edit */\nwindow.RF_RATE_CARDS = %s;\n" % blob)
write(os.path.join(ROOT, "deploy", "rates.gen.js"),
      u"// GENERATED by tools/gen-rates.py from data/rate-cards.json — do not edit\nexport const RATES = %s;\n" % blob)

unsigned = [c["id"] for c in cards if c.get("status") != "contracted"]
print("rate cards: %d (%s) -> assets/rate-cards.js, deploy/rates.gen.js"
      % (len(cards), ("UNSIGNED: " + ", ".join(unsigned)) if unsigned else "all contracted"))
