"""Generate the shipping rate cards for the browser and the Worker from the one contracted source.

    python tools/gen-rates.py

    data/rate-cards.json  ->  assets/rate-cards.js   (window.RF_RATE_CARDS, loaded by assets/shipping.js)
                          ->  deploy/rates.gen.js    (export const RATES, bundled into the Worker)

There is exactly one copy of the contracted numbers. The shop, the price export and the API all compute shipping from
this file, so a customer's quoted price and the server's re-priced order can never disagree about the rate.
"""
import io, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(ROOT, "data", "rate-cards.json")
data = json.load(io.open(src, encoding="utf-8"))

cards = data.get("cards", [])
assert cards, "no rate cards"
for c in cards:
    for k in ("id", "mode", "origin", "destination", "unit", "effectiveFrom", "tiers", "transitMinDays", "transitMaxDays"):
        assert c.get(k) not in (None, "", []), "%s is missing %s" % (c.get("id"), k)
    assert c["mode"] in ("air", "sea"), c["id"]
    assert c.get("status") in ("draft", "contracted", "expired"), "%s has a bad status" % c["id"]
    tiers = c["tiers"]
    assert tiers == sorted(tiers, key=lambda t: t["from"]), "%s tiers must ascend by 'from'" % c["id"]
    assert tiers[0]["from"] == 0, "%s needs a tier starting at 0" % c["id"]
    if c["mode"] == "air":
        assert c.get("volumetricDivisor", 0) > 0, "%s needs a volumetric divisor" % c["id"]
    # Pooling: a single order is priced as its share of the consignment it rides in, not as a shipment of its own.
    # Leaving it unset keeps the old per-basket behaviour, so this can be turned off by deleting one number.
    tc = c.get("typicalConsignment")
    if tc is not None:
        assert isinstance(tc, (int, float)) and tc > 0, "%s typicalConsignment must be a positive number" % c["id"]
        assert tc >= (c.get("minimumBillable") or 0), "%s typicalConsignment is below its own minimum billable" % c["id"]

# ---- import clearance: duty bands and the per-shipment fees, from the same one source
cus = json.load(io.open(os.path.join(ROOT, "data", "customs.json"), encoding="utf-8"))
assert cus.get("status") in ("draft", "confirmed"), "customs status must be draft or confirmed"
assert cus.get("basis") == "CIF", "duty is assessed on CIF; changing that changes the pricing maths"
bands = {k: v for k, v in cus.get("dutyBands", {}).items() if not k.startswith("_")}
assert bands.get("_default") is not None or "_default" in cus.get("dutyBands", {}), "customs needs a _default band"
for k, v in bands.items():
    assert isinstance(v, (int, float)) and 0 <= v < 1, "duty band %s must be a fraction, got %r" % (k, v)
for m, f in cus.get("perConsignment", {}).items():
    if m.startswith("_"): continue
    assert f.get("typical", 0) > 0, "%s needs a typical consignment size to share clearance over" % m
    assert f.get("typicalUnit") in ("kg", "cbm"), "%s typicalUnit must be kg or cbm" % m
customs = {
    "status": cus["status"], "basis": cus["basis"], "entry": cus.get("entry", {}),
    "dutyBands": {**bands, "_default": cus["dutyBands"].get("_default", 0.05)},
    "perConsignment": {m: {"typical": f["typical"], "typicalUnit": f["typicalUnit"],
                           "fees": {k: v for k, v in f["fees"].items() if not k.startswith("_")}}
                       for m, f in cus.get("perConsignment", {}).items() if not m.startswith("_")},
    "excluded": cus.get("excluded", []),
}

# the browser and the Worker get the cards, the density table and the clearance rules; prose notes stay out
payload = {"cards": cards, "packedDensity": {k: v for k, v in data.get("packedDensity", {}).items() if not k.startswith("_")},
           "customs": customs}
blob = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))

def write(path, text):
    tmp = path + ".tmp"
    io.open(tmp, "w", encoding="utf-8").write(text)
    os.replace(tmp, path)

write(os.path.join(ROOT, "assets", "rate-cards.js"),
      u"/* GENERATED by tools/gen-rates.py from data/rate-cards.json — do not edit */\nwindow.RF_RATE_CARDS = %s;\n" % blob)
write(os.path.join(ROOT, "deploy", "rates.gen.js"),
      u"// GENERATED by tools/gen-rates.py from data/rate-cards.json — do not edit\nexport const RATES = %s;\n" % blob)

unsigned = [c["id"] for c in cards if c.get("status") != "contracted"]
print("rate cards: %d (%s) -> assets/rate-cards.js, deploy/rates.gen.js"
      % (len(cards), ("UNSIGNED: " + ", ".join(unsigned)) if unsigned else "all contracted"))
print("customs: %d duty bands, clearance fees for %s (%s)"
      % (len(bands) - 1, "/".join(sorted(customs["perConsignment"])), 
         "UNCONFIRMED - no broker has signed off" if customs["status"] != "confirmed" else "confirmed"))
for m, f in sorted(customs["perConsignment"].items()):
    tot = sum(f["fees"].values())
    print("  %s clearance: $%g shared over %g %s = $%.3f/%s" % (m, tot, f["typical"], f["typicalUnit"], tot / f["typical"], f["typicalUnit"]))
